# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c71fbf759242921e1cd76cd006a1a89c53cf0b74ed63ff3556b12f9dac8a5f99c48fa846520a1af09eae4e8de071617e06988daf53d27f2c59eb78769a626c26

test:
  secret_key_base: 159848b202f9461ea3c7f00e93e9f96457d3269a8a228e18ce6c55c42bc054fbf25ce311f43a12d734bde482f4b712ee5b8610f6e4135454d38d781fe01ac40a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
